import Head from 'next/head';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio Fotografo.</title>
        <meta name="description" content="Generated by create next app" />
        <div>
          Hello next app 
        </div>
      </Head>
    </div>
  )
}
